# Generated by Django 5.0.2 on 2024-09-26 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agriapp', '0003_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='confirm_password',
        ),
    ]
