# Generated by Django 5.0.2 on 2024-09-27 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agriapp', '0004_remove_users_confirm_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Requirements',
        ),
    ]
