# Generated by Django 5.1.1 on 2024-10-01 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agriapp', '0008_services'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Services',
        ),
    ]
