# Generated by Django 5.1.1 on 2024-10-01 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriapp', '0009_delete_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('overview', models.TextField()),
                ('key_features', models.TextField()),
            ],
        ),
    ]
