# Generated by Django 5.1.1 on 2024-10-31 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriapp', '0010_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='image',
            field=models.ImageField(blank=True, default='images/background.jpeg', null=True, upload_to='images/'),
        ),
    ]
