# Generated by Django 5.1.1 on 2024-10-31 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agriapp', '0011_services_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='image',
        ),
    ]
